### ISSUE TITLE
It does clonal vs suclonal variants? 

### ISSUE THREAD

**Issue by immuneAI** [google/deepsomatic#2]
Hi, 
It's a great tool using the neural network approach. Could you clarify, does this tool classifies somatic clonal and subclonal variants? Or it classify germline variants vs. somatic variants?

Thanks again!!

**Comment by kishwarshafin** [comment]
Hi @immuneAI ,

clonal vs subclonal variant would require clustering the reads which is not implemented in DeepSomatic. Currently we only do germline vs somatic.

**Comment by immuneAI** [comment]
Thanks, I saw the LinkedIn [post](https://www.linkedin.com/feed/update/urn:li:activity:7122629459425296385?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A7122629459425296385%29
) of Andrew, stating it does subclonal variant, guess it's a typo!!

**Comment by AndrewCarroll** [comment]
Hi @immuneAI 

This is due to me not choosing my words as exactly as possible. 

I wanted to use the word "subclonal" to suggest that the method can potentially be inclusive of non-cancer applications where you want to identify variants in populations of cells. For example, cases like CHIP, detecting CRISPR edits, or cases where you have a population of mostly genetically identical organisms like bacteria colonies that carry a low rate of variants within them. 

I didn't think about how that distinction that would be read for cancer applications specifically. 

DeepSomatic detects somatic variants, but it is not itself capable of distinguishing which are clonal and which are subclonal from within the tumor BAM file. DeepSomatic will flag either of those classes as somatic variants, but you would need some other process to determine which are clonal to the tumor and which are subclonal within it.

I hope that explanation clarifies what DeepSomatic is designed for.
