### ISSUE TITLE
Variant not called by DeepSomatic

### ISSUE THREAD

**Issue by minw2828** [google/deepsomatic#37]
Hello, 

I hope you are doing well.

I am writing to you to understand why DeepSomatic did not call a variant.

As shown in the IGV screenshot below:

- In the variant track, the variant was called by another caller (1st panel) but wasn't called by DeepSomatic (2nd panel). 
- In alignment tracks, the variant is present in the tumour bam files that were provided as input to another caller (1st panel) and DeepSomatic (2nd panel). 
- In the alignment tracks, the variant is absent in the normal bam files that were provided as input to another caller (4th panel) and DeepSomatic (3rd panel).

Our pipeline only filtered out non-PASS DeepSomatic variants. Given the clean alignments (MAPQ: 60) in this genomic region, and 12 reads out of 28 reads carried this variant, I expect the variant would be PASS if it was called. 

Would you have any thoughts on why DeepSomatic did not call the variant? 

![Image](https://github.com/user-attachments/assets/7e02acec-8440-4ef5-a9d3-2af98b83f694)

Many thanks,
Min

**Comment by pichuan** [comment]
Hi @minw2828 ,
Can you check the output VCF and see if the candidate is in the file, or is it completely absent from the VCF file?
If it's in the VCF, can you paste that line here so we can take a look?

Thanks!

-pichuan

**Comment by minw2828** [comment]
Hi @pichuan,

Thank you for your quick reply. 

I confirmed that the variant was absent in the DeepSomatic output VCF file. 

Many thanks,
Min

**Comment by pichuan** [comment]
Thanks @minw2828 . Can you share the command you run?

I would assume that you can't share a small chunk for your BAMs for debugging, but maybe we can check your command first.

**Comment by minw2828** [comment]
Hi @pichuan, 

Please find attached the commands. 

[deepsomatic.wdl.txt](https://github.com/user-attachments/files/18105054/deepsomatic.wdl.txt)

Many thanks,
Min

**Comment by AndrewCarroll** [comment]
Hi @minw2828 

I see that you have a filter for PASS step in the WDL command. This will remove variant sites which the neural network determines are Reference or Germline. Could you run the command without that filter step and let us know if this position has an entry in the VCF that is filtered?

This would be very helpful for us in determining if the issue here is that a candidate was not generated, which would be an issue with the heuristics we write to find possible positions, or if the neural network made the call either because it has learned something which indicates this isn't a variant or because there is some other issue if it is.

As Pi-Chuan mentions, a BAM snippet that would let us replicate this would be the most helpful.

In general, for PacBio when a variant that looks like it should be called is not called, we have sometimes observed that the read phasing is responsible - that is that the apparent variant appears on both haplotypes as determined by germline phasing. I am not sure if you are able to visualize the phasing information, but this is often useful to see for pacbio data as well.

**Comment by minw2828** [comment]
Hi @AndrewCarroll ,

Thank you for sharing the info with me. 

I have rerun the DeepSomatic command (attached) as you advised. 
[deepsomatic.wdl.txt](https://github.com/user-attachments/files/18109193/deepsomatic.wdl.txt)

As you expected, DeepSomatic has called the variant but did not classify it as PASS. 
`chr13   32336307        .       A       ATTCTG  1.4     RefCall .       GT:GQ:DP:AD:VAF:PL      ./.:6:24:16,8:0.333333:0,23,4`

The HiPhase tool did not phased the variant into two haplotypes. Please let me know how to visualize how DeepSomatic phased the variant. 

I provided the mapped.bam (unphased) to DeepSomatic, not a phased bam.

The attached snippet is the hiphase-phased bam 1kb surround the variant. 
[snippet.zip](https://github.com/user-attachments/files/18109178/snippet.zip)

Hope this helps. 

Many thanks,
Min

**Comment by minw2828** [comment]
Hello @AndrewCarroll ,

When I used DeepSomatic (v1.8.0), the variant has become PASS. 
`chr13   32336307        .       A       ATTCTG  16.3    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:16:24:16,8:0.333333:16,29,0`

Thank you! 

Cheers,
Min

**Comment by pichuan** [comment]
Thank you @minw2828 . Good to know that v1.8.0 got this variant. We've made several improvements in 1.8.0, so it'll be better to use the latest version.
Please feel free to provide more feedback and ask questions here in the future!
